services:
  postgres:
    image: postgres:15-alpine
    container_name: naijapay-postgres
    environment:
      POSTGRES_DB: naijapay
      POSTGRES_USER: naijapay
      POSTGRES_PASSWORD: naijapay123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U naijapay"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - naijapay_network

  redis:
    image: redis:7-alpine
    container_name: naijapay-redis
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - naijapay_network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: naijapay-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: naijapay
      RABBITMQ_DEFAULT_PASS: naijapay123
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - naijapay_network

  transaction-service:
    build: ./services/transaction-service
    container_name: naijapay-transaction-service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://naijapay:naijapay123@postgres:5432/naijapay
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://naijapay:naijapay123@rabbitmq:5672/
      
      TRANSACTION_SERVICE_URL: http://transaction-service:8000
      WALLET_SERVICE_URL: http://localhost:8002
      FRAUD_SERVICE_URL: http://localhost:8003
      JWT_SECRET_KEY: super-secret-key-change-in-production-2026
      SERVICE_NAME: transaction-service
      PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./services/transaction-service:/app
    networks:
      - naijapay_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  naijapay_network:
    driver: bridge